### PR TITLE
Trailing comma issue

### LINKED ISSUE #8: Trailing comma and missing font file when only woff file availible
When only having the `woff` file in the folder and the `checkPath` option enabled, slightly incorrect (and invalid) CSS is generated:

```
@font-face {
    font-family: 'Proxima Nova';
    src: url(../fonts/proximanova-regularit-webfont.eot);
    src: url(../fonts/proximanova-regularit-webfont.woff) format('woff'),;
    font-weight: 400;
    font-style: italic
}
```

Note the `eot` is still included and the extra comma after `('woff')`. Does https://github.com/seaneking/postcss-fontpath/pull/4 address these issues?

### PR DESCRIPTION
**Pull request by mikestreety**
So after saying I wasn't confident enough I gave this a crack.

Seems to work in the tests I've done. I'm not quite sure about the tests in the repo so haven't updated those yet.

For me, this fixes #8 and #7

I've also updated to postcss 6.

Again, this has only been tested by me but seems to work

### CODE REVIEW

**Comment by madeleineostoja** [comment]
👍 Thanks for this! I'll pull it down and wire up a few tests when I get a mo.

**Comment by madeleineostoja** [comment]
Tests are failing for me (Node 7), only had a quick look but few things:

- [ ] Object assign only shallow merges, so merging empty opts onto `formats` gives you undefined and errors out. Either recursively Object.assign or use something like https://github.com/KyleAMathews/deepmerge

- [ ] PostCSS 6+ only supports Node 4+, so no need to polyfill Object.assign

- [ ] Output src spacing is clobbered, that was the point of [this conditional](https://github.com/seaneking/postcss-fontpath/blob/master/index.js#L51)

- [ ] Should define defaults in a constant outside the export, rather than inline (code cleanliness)

- [ ] I think showMissingFontError shouldn't be an option, and we just silently exclude the font. That's kind the point of checkPath

Other stuff, could be done separate to PR but if you feel comfortable doing would be great to have: 

- Might as well add in the `iefix` option from https://github.com/seaneking/postcss-fontpath/pull/4 while we're here

- Need basic documentation of new opts in README

**Comment by mikestreety** [comment]
Hey, thanks for the feedback!

- The output src "clobbering" is that because of a lack of new lines? If so, we can add a new line in the `join`.

- The `showMissingFont` error var, I agree. On this version, we have it disabled anyway! Just didn't want to take it out.

With the other bits, I was just butchering your code 😉. Happy to do the two above and the readme up. The `ieFix` option gets solved in this as you just wouldn't include an eot file?

**Comment by madeleineostoja** [comment]
> The output src "clobbering" is that because of a lack of new lines?

Yep newline and spacing

> The ieFix option gets solved in this as you just wouldn't include an eot file?

If you have a woff file then you don't need an eot, since IE 8+ supports woff and it's a better format, but still probably worth having IE8 support conditional now since it's such an edge case to support. Should probably have an `ie8Fix` or something option off by default, even if you're not providing a formats array or path checking, since this will be a breaking version bump anyway (since it uses PostCSS 6)

**Comment by mikestreety** [comment]
Done a few updates this afternoon:

- Output no longer clobbered
- Uses `deepmerge` instead of objectAssign (and removed objectAssign fallback)
- Moved defaults outside of export
- Removed output/error when font not found

Yet to:

- Update tests (mind if I leave this one to you?)
- Update documentation
- Implement ie fix

**Comment by madeleineostoja** [comment]
Looks good! Thanks. Yep I can update tests.

Also if checkpath is robust enough should probably be enabled by default, but will see how it works when I pull it down.

**Comment by mikestreety** [comment]
Great, thanks!

**Comment by madeleineostoja** [comment]
Will merge this into master and fix up those last issues later

**Comment by mikestreety** [comment]
Thanks for smashing it!

**Comment by madeleineostoja** [comment]
Just pushed up 1.0 with all changes

**Pull request merged**
